#: kivy 1.9
#: import ScreenManager kivy.uix.screenmanager.ScreenManager
#: import Screen kivy.uix.screenmanager.ScreenManager
#: import NewGameScreen screen
#: import LoadGameScreen screen

ScreenManager:
    id: screen_manager
    #transition: FadeTransition()
    ListMangaScreen:
        id: listmanga_screen
        name: 'ListMangaScreen'
        manager: 'screen_manager'
    NewGameScreen:
        id: newgame_screen
        name: 'NewGameScreen'
        manager: 'screen_manager'

<CustomButtonChapter@Button>:
    chapter : 'chapter'
    update_chapter: 'updated'
    GridLayout:
        height: "50dp" # match the button's height
        width: self.parent.width                  # set to whatever you would like
        pos: self.parent.pos
        pos_hint:{'top':0}
        cols: 1
        BoxLayout:
            orientation:"horizontal"
            height: self.parent.height # match the button's height
            width: self.parent.width                  # set to whatever you would like
            pos: self.parent.pos
            pos_hint:{'top':0}
            spacing : "5dp"
            padding : "5dp"
            Label:
                font_size: 17
                pos: self.parent.pos
                text:root.chapter
                text_size: self.width, None
                halign:'left'
                height: self.texture_size[1]
            Label:
                font_size: 17
                pos: self.parent.pos
                text:root.update_chapter
                text_size: self.width, None
                halign:'right'
                height: self.texture_size[1]


<CustomButton@Button>:
    image_source: 'assasin-sword-1.jpeg'
    title: ''
    image_id:'test'
    last_chapter:'Ch.'
    last_updated:'Updated'
    GridLayout:
        height: self.parent.height # match the button's height
        width: self.parent.width                  # set to whatever you would like
        pos: self.parent.pos
        pos_hint:{'top':0}
        cols: 1
        BoxLayout:
            orientation:"vertical"
            height: self.parent.height # match the button's height
            width: self.parent.width                  # set to whatever you would like
            pos: self.parent.pos
            pos_hint:{'top':0}
            BoxLayout:
                orientation: "horizontal"
                AsyncImage:
                    id: root.image_id
                    source: root.image_source
                    size_hint_x: 1
                    size_hint_y:1
                    allow_stretch: True
            BoxLayout:
                orientation:"vertical"
                size_hint : 1,.3
                BoxLayout:
                    orientation:"horizontal"
                    Label:
                        font_size: 17
                        pos: self.parent.pos
                        text:root.title
                        text_size: self.width, None
                        halign:'center'
                        height: self.texture_size[1]
                BoxLayout:
                    orientation:"horizontal"
                    size_hint : 1,.3
                    BoxLayout:
                        orientation:"horizontal"
                        Label:
                            font_size: 12
                            text:root.last_updated
                    BoxLayout:
                        orientation:"horizontal"
                        Label:
                            font_size: 12
                            text: root.last_chapter


<ListMangaScreen>:
    ScrollView:
        GridLayout:
            id: listManga_id
            size_hint : 1,None
            height: self.minimum_height
            width: self.minimum_width
            cols:3
            spacing : "20dp"
            padding : "20dp"

            Button:
                id: remove_id
                orientation: "vertical"
                size_hint: 1,None
                height: "400dp"
                elevation: 5
                border_radius: 20
                radius: [15]
<NewGameScreen>:
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            orientation: 'vertical'
            size_hint : 1,None
            BoxLayout:
                orientation:'horizontal'
                Button:
                    text:'<-'
                    size_hint: None,None
                    on_release: app.root.current = "ListMangaScreen"
                Label:
                    id: mangatittle_id
                    text: 'Game Length in Days'
                    text_size: self.width, None
                    halign:'center'
                    height: self.texture_size[1]
                    font_size: 30
#            BoxLayout:
#                orientation: 'horizontal'
#                ToggleButton:
#                    text: 'information'
#                    group: 'newgame_days'
#                    font_size: 30
#                ToggleButton:
#                    text: 'chapter'
#                    group: 'newgame_days'
#                    font_size: 30
        BoxLayout:
            orientation: 'horizontal'
            AsyncImage:
                id:icon_id
                source: ''
                # Giving the size of image
                size_hint_x: 0.4

                # allow stretching of image
                allow_stretch: True
            ScrollView:
                GridLayout:
                    id: listChapter_id
                    size_hint : 1,None
                    height: self.minimum_height
                    width: self.minimum_width
                    cols:1
                    spacing : "1dp"
                    padding : "20dp"

